version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: mysql_todolist
    # networks:
    #   - development-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# networks:
#   development-network:
#     driver: bridge

# volumes:
#   mysql_data:
#     driver: local
